name: persistent-example
version: '0.1.0.0'

dependencies:
- base >=4.7 && <5
- monad-logger
- persistent
- persistent-sqlite
- persistent-postgresql
- persistent-template

executables:
  persistent-example:
    main: Main.hs
    source-dirs: src
